import React, { createContext, useState, useContext } from 'react';

export const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en'); // 'en' or 'de'

  const dictionary = {
    en: {
      "GOOD MORNING": "GOOD MORNING",
      "HELLO": "HELLO",
      "GOOD EVENING": "GOOD EVENING",
      "WELCOME BACK, ATHLETE. YOUR DAILY TARGET IS SYNCHRONIZED.": "WELCOME BACK, ATHLETE. YOUR DAILY TARGET IS SYNCHRONIZED.",
      "Dashboard": "Dashboard",
      "Workouts": "Workouts",
      "Analytics": "Analytics",
      "Settings": "Settings",
      "About Us": "About Us",
      "Support": "Support",
      "ACCOUNT": "ACCOUNT",
      "SETTINGS": "SETTINGS",
      "START WORKOUT": "START WORKOUT",
      "SEARCH...": "SEARCH...",
      "Member": "Member",
      "DAILY GOAL": "DAILY GOAL",
      "ACTIVE RECOVERY": "ACTIVE RECOVERY",
      "ELITE TRACK": "ELITE TRACK",
      "Quote of the day: Consistency beats motivation": "Quote of the day: Consistency beats motivation",
      "STAY HYDRATED": "STAY HYDRATED",
      "1.2L more for peak efficiency.": "1.2L more for peak efficiency.",
      "GOAL: 3.5L DAILY": "GOAL: 3.5L DAILY",
      "{amount}L more for peak efficiency.": "{amount}L more for peak efficiency.",
      "GOAL: {amount}L DAILY": "GOAL: {amount}L DAILY",
      "Close hydration info": "Close hydration info",
      "WATER FUELS PERFORMANCE": "WATER FUELS PERFORMANCE",
      "Your body depends on hydration for muscle performance, recovery, focus and efficient energy use. Even slight dehydration can lower your output before you notice it.": "Your body depends on hydration for muscle performance, recovery, focus and efficient energy use. Even slight dehydration can lower your output before you notice it.",
      "MUSCLE PERFORMANCE": "MUSCLE PERFORMANCE",
      "Water supports strength, recovery and clean training output from warm-up to last set.": "Water supports strength, recovery and clean training output from warm-up to last set.",
      "FAT METABOLISM": "FAT METABOLISM",
      "Hydration helps your body process nutrients and burn energy more efficiently.": "Hydration helps your body process nutrients and burn energy more efficiently.",
      "FOCUS & ENERGY": "FOCUS & ENERGY",
      "Low hydration can reduce concentration, mood and physical performance.": "Low hydration can reduce concentration, mood and physical performance.",
      "DAILY TARGET": "DAILY TARGET",
      "Recommended: 2.5L - 3.5L": "Recommended: 2.5L - 3.5L",
      "Decrease hydration goal": "Decrease hydration goal",
      "Hydration goal in liters": "Hydration goal in liters",
      "Increase hydration goal": "Increase hydration goal",
      "Go higher on intense training days, hot days or long cardio sessions.": "Go higher on intense training days, hot days or long cardio sessions.",
      "HYDRATION GOAL": "HYDRATION GOAL",
      "DAILY WATER TARGET": "DAILY WATER TARGET",
      "ADVANCED DATA": "ADVANCED DATA",
      "ENCRYPTION PROTOCOL": "ENCRYPTION PROTOCOL",
      "HYDRATION REMINDER": "HYDRATION REMINDER",
      "ALERT SETTINGS": "ALERT SETTINGS",
      "Time to drink water. Keep your daily target on track.": "Time to drink water. Keep your daily target on track.",
      "Morning, midday and evening reminder": "Morning, midday and evening reminder",
      "Demo reminder": "Demo reminder",
      "Hydration reminders are scheduled for morning, midday and evening.": "Hydration reminders are scheduled for morning, midday and evening.",
      "SHOW DEMO REMINDER": "SHOW DEMO REMINDER",
      "Dismiss reminder": "Dismiss reminder",
      "WORKOUT REMINDER": "WORKOUT REMINDER",
      "Your daily session prompt is ready. Keep the streak alive.": "Your daily session prompt is ready. Keep the streak alive.",
      "Daily session prompt": "Daily session prompt",
      "WHAT IS BMI?": "WHAT IS BMI?",
      "SAVE": "SAVE",
      "BMI OFF": "BMI OFF",
      "BODY MASS INDEX": "BODY MASS INDEX",
      "Close BMI info": "Close BMI info",
      "BMI is a simple value calculated from your height and weight. It gives a rough reference point for body composition, but it is not a full health analysis.": "BMI is a simple value calculated from your height and weight. It gives a rough reference point for body composition, but it is not a full health analysis.",
      "HOW IT WORKS": "HOW IT WORKS",
      "Your weight is divided by your height squared, then placed into broad categories such as underweight, normal weight or overweight.": "Your weight is divided by your height squared, then placed into broad categories such as underweight, normal weight or overweight.",
      "IMPORTANT TO KNOW": "IMPORTANT TO KNOW",
      "BMI does not consider muscle mass, body composition, genetics or athletic performance. A strong athlete can have a higher BMI and still be fit and healthy.": "BMI does not consider muscle mass, body composition, genetics or athletic performance. A strong athlete can have a higher BMI and still be fit and healthy.",
      "USE IT AS A REFERENCE": "USE IT AS A REFERENCE",
      "Numbers can guide you. They do not define you.": "Numbers can guide you. They do not define you.",
      "BMI REFERENCE RANGES": "BMI REFERENCE RANGES",
      "For adults, these ranges are commonly used as a broad orientation. Your training level, muscle mass and overall health context still matter.": "For adults, these ranges are commonly used as a broad orientation. Your training level, muscle mass and overall health context still matter.",
      "LOW": "LOW",
      "GOOD": "GOOD",
      "MEDIUM": "MEDIUM",
      "HIGH": "HIGH",
      "Under 18.5": "Under 18.5",
      "Often classified as underweight.": "Often classified as underweight.",
      "Usually considered the healthy weight range.": "Usually considered the healthy weight range.",
      "Often classified as overweight, depending on context.": "Often classified as overweight, depending on context.",
      "30.0 and above": "30.0 and above",
      "Often classified as obesity and worth discussing in context.": "Often classified as obesity and worth discussing in context.",
      "STEPS": "STEPS",
      "ACTIVE FLOW": "ACTIVE FLOW",
      "CALORIES": "CALORIES",
      "BURN RATE": "BURN RATE",
      "OPTIMAL": "OPTIMAL",
      "TIME": "TIME",
      "TIME IN ZONE": "TIME IN ZONE",
      "MINUTES": "MINUTES",
      "MIN": "MIN",
      "ACHIEVEMENTS": "ACHIEVEMENTS",
      "MEDALS EARNED": "MEDALS EARNED",
      "IMPRESSUM": "IMPRINT",
      "DATENSCHUTZ": "PRIVACY POLICY",
      "PAGE_IMPRINT_TITLE": "IMPRINT",
      "PAGE_IMPRINT_DESC": "Legal information and disclosures.",
      "PAGE_PRIVACY_TITLE": "PRIVACY POLICY",
      "PAGE_PRIVACY_DESC": "We prioritize your data security as much as your personal bests.",
      "SUN": "SUN",
      "MON": "MON",
      "TUE": "TUE",
      "WED": "WED",
      "THU": "THU",
      "FRI": "FRI",
      "SAT": "SAT",
      "COMPLETED": "COMPLETED",
      "LATEST ACHIEVEMENT": "LATEST ACHIEVEMENT",
      "You've maintained a top 5% strength-to-weight ratio worldwide for 12 consecutive weeks.": "You've maintained a top 5% strength-to-weight ratio worldwide for 12 consecutive weeks.",
      "DEADLIFT": "DEADLIFT",
      "SQUAT": "SQUAT",
      "BENCH": "BENCH",
      "NEW PR": "NEW PR",
      "SET": "SET",
      "Default reps": "Default reps",
      "Enter reps for every set.": "Enter reps for every set.",
      "REPS PER SET": "REPS PER SET",
      "Customize each set individually": "Customize each set individually"
    },
    de: {
      "GOOD MORNING": "GUTEN MORGEN",
      "HELLO": "HALLO",
      "GOOD EVENING": "GUTEN ABEND",
      "WELCOME BACK, ATHLETE. YOUR DAILY TARGET IS SYNCHRONIZED.": "WILLKOMMEN ZURÜCK, ATHLET. DEIN TAGESZIEL IST SYNCHRONISIERT.",
      "Dashboard": "Dashboard",
      "Workouts": "Workouts",
      "Analytics": "Analysen",
      "Settings": "Einstellungen",
      "About Us": "Über uns",
      "Support": "Support",
      "START WORKOUT": "WORKOUT STARTEN",
      "SEARCH...": "SUCHE...",
      "Member": "Mitglied",
      "DAILY GOAL": "TAGESZIEL",
      "ACTIVE RECOVERY": "AKTIVE ERHOLUNG",
      "ELITE TRACK": "ELITE-PFAD",
      "Quote of the day: Consistency beats motivation": "Zitat des Tages: Beständigkeit schlägt Motivation",
      "STAY HYDRATED": "BLEIB HYDRIERT",
      "1.2L more for peak efficiency.": "Noch 1.2L für maximale Effizienz.",
      "GOAL: 3.5L DAILY": "ZIEL: 3.5L TÄGLICH",
      "{amount}L more for peak efficiency.": "Noch {amount}L für maximale Effizienz.",
      "GOAL: {amount}L DAILY": "ZIEL: {amount}L TÄGLICH",
      "Close hydration info": "Hydration-Info schließen",
      "WATER FUELS PERFORMANCE": "WASSER TREIBT PERFORMANCE AN",
      "Your body depends on hydration for muscle performance, recovery, focus and efficient energy use. Even slight dehydration can lower your output before you notice it.": "Dein Körper braucht Hydration für Muskelperformance, Regeneration, Fokus und effiziente Energienutzung. Schon leichte Dehydrierung kann deinen Output senken, bevor du es bewusst merkst.",
      "MUSCLE PERFORMANCE": "MUSKELPERFORMANCE",
      "Water supports strength, recovery and clean training output from warm-up to last set.": "Wasser unterstützt Kraft, Regeneration und saubere Trainingsleistung vom Warm-up bis zum letzten Satz.",
      "FAT METABOLISM": "FETTSTOFFWECHSEL",
      "Hydration helps your body process nutrients and burn energy more efficiently.": "Hydration hilft deinem Körper, Nährstoffe zu verarbeiten und Energie effizienter zu verbrennen.",
      "FOCUS & ENERGY": "FOKUS & ENERGIE",
      "Low hydration can reduce concentration, mood and physical performance.": "Zu wenig Flüssigkeit kann Konzentration, Stimmung und körperliche Leistung reduzieren.",
      "DAILY TARGET": "TAGESZIEL",
      "Recommended: 2.5L - 3.5L": "Empfohlen: 2.5L - 3.5L",
      "Decrease hydration goal": "Trinkziel verringern",
      "Hydration goal in liters": "Trinkziel in Litern",
      "Increase hydration goal": "Trinkziel erhöhen",
      "Go higher on intense training days, hot days or long cardio sessions.": "Setze es höher an intensiven Trainingstagen, heißen Tagen oder bei langen Cardio-Einheiten.",
      "STEPS": "SCHRITTE",
      "ACTIVE FLOW": "AKTIVER FLUSS",
      "CALORIES": "KALORIEN",
      "BURN RATE": "VERBRENNUNGSRATE",
      "OPTIMAL": "OPTIMAL",
      "TIME": "ZEIT",
      "TIME IN ZONE": "ZEIT IN ZONE",
      "MINUTES": "MINUTEN",
      "MIN": "MIN",
      "ACHIEVEMENTS": "ERFOLGE",
      "MEDALS EARNED": "MEDAILLEN VERDIENT",
      "IMPRESSUM": "IMPRESSUM",
      "DATENSCHUTZ": "DATENSCHUTZ",
      "PAGE_IMPRINT_TITLE": "IMPRESSUM",
      "PAGE_IMPRINT_DESC": "Rechtliche Angaben und Hinweise.",
      "PAGE_PRIVACY_TITLE": "DATENSCHUTZ",
      "PAGE_PRIVACY_DESC": "Wir behandeln deine Daten mit höchster Sorgfalt.",
      "SUN": "SO",
      "MON": "MO",
      "TUE": "DI",
      "WED": "MI",
      "THU": "DO",
      "FRI": "FR",
      "SAT": "SA",
      "COMPLETED": "ABGESCHLOSSEN",
      "LATEST ACHIEVEMENT": "NEUESTER ERFOLG",
      "You've maintained a top 5% strength-to-weight ratio worldwide for 12 consecutive weeks.": "Du hast für 12 aufeinanderfolgende Wochen ein weltweites Top-5% Kraft-Gewichts-Verhältnis beibehalten.",
      "DEADLIFT": "KREUZHEBEN",
      "SQUAT": "KNIEBEUGEN",
      "BENCH": "BANKDRÜCKEN",
      "NEW PR": "NEUER PR",
      "TOP 5%": "TOP 5%",
      "TOP 10%": "TOP 10%",
      "CREATE YOUR OWN": "ERSTELLE DEIN EIGENES",
      "WORKOUT": "WORKOUT",
      "BUILD YOUR OWN PLAN": "ERSTELLE DEINEN EIGENEN PLAN",
      "EDIT YOUR PLAN": "BEARBEITE DEINEN PLAN",
      "DELETE WORKOUT": "WORKOUT LÖSCHEN",
      "WORKOUT NAME (E.G. MONDAY OLYMPIC LIFTING)": "WORKOUT-NAME (Z. B. MONTAG OLYMPISCHES HEBEN)",
      "Please enter a workout name.": "Bitte gib einen Workout-Namen ein.",
      "PLAN ICON": "PLAN-ICON",
      "WORKOUT COVER IMAGE": "WORKOUT-TITELBILD",
      "UPLOAD COVER PHOTO": "TITELBILD HOCHLADEN",
      "CHANGE COVER PHOTO": "TITELBILD ÄNDERN",
      "PNG, JPG UP TO 10MB": "PNG, JPG BIS 10 MB",
      "Exercise Name...": "Übungsname...",
      "Delete exercise": "Übung löschen",
      "Move exercise": "Übung verschieben",
      "SETS": "SÄTZE",
      "SET": "SATZ",
      "REPS": "WDH.",
      "REST (S)": "PAUSE (S)",
      "NOTES": "NOTIZEN",
      "Enter an exercise name.": "Gib einen Übungsnamen ein.",
      "Enter sets.": "Gib Sätze ein.",
      "Enter reps.": "Gib Wiederholungen ein.",
      "Default reps": "Standard-Wdh.",
      "Enter reps for every set.": "Gib Wiederholungen für jeden Satz ein.",
      "REPS PER SET": "WDH. PRO SATZ",
      "Customize each set individually": "Passe jeden Satz einzeln an",
      "ADD EXERCISE": "ÜBUNG HINZUFÜGEN",
      "SAVE WORKOUT": "WORKOUT SPEICHERN",
      "UPDATE WORKOUT": "WORKOUT AKTUALISIEREN",
      "Add at least one exercise to save your workout.": "Füge mindestens eine Übung hinzu, um dein Workout zu speichern.",
      "SELF-MADE WORKOUT PLANS": "SELBST ERSTELLTE WORKOUT-PLÄNE",
      "Your custom training foundations.": "Deine eigenen Trainingsgrundlagen.",
      "READY-MADE WORKOUT PLANS": "FERTIGE WORKOUT-PLÄNE",
      "Curated high-performance foundations.": "Kuratierte Grundlagen für starke Performance.",
      "CUSTOM PLAN": "EIGENER PLAN",
      "ADVANCED PLAN": "FORTGESCHRITTENEN-PLAN",
      "BEGINNER PLAN": "ANFÄNGER-PLAN",
      "PUSH PULL LEGS": "PUSH PULL LEGS",
      "FAT LOSS": "FETTVERLUST",
      "FULL BODY WORKOUT": "GANZKÖRPER-WORKOUT",
      "Chest Press (3x12)": "Brustpresse (3x12)",
      "Incline Bench Press (3x12)": "Schrägbankdrücken (3x12)",
      "Shoulder Press (2x15)": "Schulterdrücken (2x15)",
      "Lat Pulldown (3x12)": "Latzug (3x12)",
      "Romanian Deadlift (3x10)": "Rumänisches Kreuzheben (3x10)",
      "Cable Row (4x12)": "Kabelrudern (4x12)",
      "HIIT Intervals (15m)": "HIIT-Intervalle (15 Min.)",
      "Bodyweight Squats (4x20)": "Kniebeugen mit Körpergewicht (4x20)",
      "Mountain Climbers (4x30s)": "Mountain Climbers (4x30s)",
      "Bench Press (3x12)": "Bankdrücken (3x12)",
      "Lateral Raise (4x12)": "Seitheben (4x12)",
      "Leg Press (4x10)": "Beinpresse (4x10)",
      "Seated Row (3x12)": "Sitzendes Rudern (3x12)",
      "Hamstring Curl (3x15)": "Beinbeuger (3x15)",
      "Plank Hold (3x45s)": "Plank halten (3x45s)",
      "MORE EXERCISES": "WEITERE ÜBUNGEN",
      "SHOW LESS": "WENIGER ANZEIGEN",
      "STRENGTH": "KRAFT",
      "INSIGHTS": "ANALYSEN",
      "REAL-TIME PERFORMANCE TREND": "PERFORMANCE-TREND IN ECHTZEIT",
      "STRENGTH PROGRESS": "KRAFTFORTSCHRITT",
      "vs last week": "vs. letzte Woche",
      "vs last month": "vs. letzter Monat",
      "vs last quarter": "vs. letztes Quartal",
      "NEW MILESTONE": "NEUER MEILENSTEIN",
      "BENCH PRESS +5KG": "BANKDRÜCKEN +5KG",
      "Unlocked 2h ago": "Vor 2 Std. freigeschaltet",
      "CURRENT PB": "AKTUELLE BESTLEISTUNG",
      "BENCH PRESS": "BANKDRÜCKEN",
      "SQUADS": "KNIEBEUGEN",
      "LBS": "LBS",
      "CURRENT STREAK: 12 DAYS": "AKTUELLE SERIE: 12 TAGE",
      "78% MONTHLY COMPLETION RATE": "78% MONATLICHE ABSCHLUSSRATE",
      "WEEKLY TRAINING QUALITY": "WÖCHENTLICHE TRAININGSQUALITÄT",
      "Your progress toward a perfect training week": "Dein Fortschritt zu einer perfekten Trainingswoche",
      "SUPPORT CENTER": "SUPPORT-CENTER",
      "CENTER": "CENTER",
      "FREQUENTLY ASKED QUESTIONS": "HÄUFIG GESTELLTE FRAGEN",
      "HOW DO I SYNC MY WEARABLE DEVICE?": "WIE SYNCHRONISIERE ICH MEIN WEARABLE?",
      "WHAT HAPPENS IF I MISS A SCHEDULED WORKOUT?": "WAS PASSIERT, WENN ICH EIN GEPLANTES WORKOUT VERPASSE?",
      "HOW DO I CREATE MY OWN PLAN?": "WIE ERSTELLE ICH MEINEN EIGENEN PLAN?",
      "STILL": "BRAUCHST DU",
      "NEED ASSISTANCE?": "NOCH HILFE?",
      "Our performance team is available for all users to help you reach your peak performance.": "Unser Performance-Team ist für alle Nutzer da, damit du deine Bestleistung erreichst.",
      "EMAIL US": "SCHREIB UNS",
      "SOCIAL CHANNELS": "SOCIAL CHANNELS",
      "SUBMIT A TICKET": "TICKET ERSTELLEN",
      "SUBJECT": "BETREFF",
      "What's going on?": "Worum geht es?",
      "DEPARTMENT": "ABTEILUNG",
      "TECHNICAL SUPPORT": "TECHNISCHER SUPPORT",
      "TRAINING PLAN": "TRAININGSPLAN",
      "BILLING": "ABRECHNUNG",
      "ACCOUNT": "KONTO",
      "SETTINGS": "EINSTELLUNGEN",
      "MESSAGE": "NACHRICHT",
      "Describe your issue in detail...": "Beschreibe dein Anliegen im Detail...",
      "SUBMIT REQUEST": "ANFRAGE SENDEN",
      "ACCOUNT SETTINGS": "KONTOEINSTELLUNGEN",
      "OPTIMIZE YOUR PROFILE AND INTERFACE. PREFERENCES FOR THE BEST EXPERIENCE.": "Optimiere dein Profil und deine Oberfläche. Einstellungen für die beste Erfahrung.",
      "ACCOUNT PROFILE": "KONTO-PROFIL",
      "DISPLAY NAME": "ANZEIGENAME",
      "EMAIL ADDRESS": "E-MAIL-ADRESSE",
      "PASSWORD": "PASSWORT",
      "CHANGE": "ÄNDERN",
      "ADVANCED BIOMETRICS": "ERWEITERTE BIOMETRIE",
      "GENDER": "GESCHLECHT",
      "Male": "Männlich",
      "Female": "Weiblich",
      "Other": "Divers",
      "HEIGHT (CM)": "GRÖSSE (CM)",
      "WEIGHT (KG)": "GEWICHT (KG)",
      "CALCULATE BMI": "BMI BERECHNEN",
      "AUTOMATED INDEX TRACKING": "AUTOMATISCHES INDEX-TRACKING",
      "ALERTS": "BENACHRICHTIGUNGEN",
      "WORKOUT REMINDERS": "WORKOUT-ERINNERUNGEN",
      "DAILY SESSION PROMPTS": "TÄGLICHE TRAININGSIMPULSE",
      "HYDRATION ALERTS": "TRINK-ERINNERUNGEN",
      "WATER INTAKE TRACKING": "WASSERAUFNAHME-TRACKING",
      "PRIVACY": "DATENSCHUTZ",
      "EXPORT PERSONAL DATA": "PERSÖNLICHE DATEN EXPORTIEREN",
      "DELETE ACCOUNT": "KONTO LÖSCHEN",
      "APPLE WATCH": "APPLE WATCH",
      "CONNECTED": "VERBUNDEN",
      "HEALTHKIT ENABLED": "HEALTHKIT AKTIVIERT",
      "DISCONNECT": "TRENNEN",
      "HYDRATION GOAL": "TRINKZIEL",
      "DAILY WATER TARGET": "TÄGLICHES WASSERZIEL",
      "ADVANCED DATA": "ERWEITERTE DATEN",
      "ENCRYPTION PROTOCOL": "VERSCHLÜSSELUNGSPROTOKOLL",
      "HYDRATION REMINDER": "TRINK-ERINNERUNG",
      "ALERT SETTINGS": "ALERT-EINSTELLUNGEN",
      "Time to drink water. Keep your daily target on track.": "Zeit, Wasser zu trinken. Bleib auf Kurs mit deinem Tagesziel.",
      "Morning, midday and evening reminder": "Morgens-, mittags- und abends-Erinnerung",
      "Demo reminder": "Demo-Erinnerung",
      "Hydration reminders are scheduled for morning, midday and evening.": "Trink-Erinnerungen sind für morgens, mittags und abends geplant.",
      "SHOW DEMO REMINDER": "DEMO-ERINNERUNG ZEIGEN",
      "Dismiss reminder": "Erinnerung schließen",
      "WORKOUT REMINDER": "WORKOUT-ERINNERUNG",
      "Your daily session prompt is ready. Keep the streak alive.": "Dein täglicher Trainingsimpuls ist bereit. Halte deine Serie am Laufen.",
      "Daily session prompt": "Täglicher Trainingsimpuls",
      "WHAT IS BMI?": "WAS IST BMI?",
      "SAVE": "SPEICHERN",
      "BMI OFF": "BMI AUS",
      "BODY MASS INDEX": "BODY MASS INDEX",
      "Close BMI info": "BMI-Info schließen",
      "BMI is a simple value calculated from your height and weight. It gives a rough reference point for body composition, but it is not a full health analysis.": "BMI ist ein einfacher Wert aus deiner Größe und deinem Gewicht. Er gibt dir eine grobe Orientierung zur Körperzusammensetzung, ist aber keine vollständige Gesundheitsanalyse.",
      "HOW IT WORKS": "SO FUNKTIONIERT ES",
      "Your weight is divided by your height squared, then placed into broad categories such as underweight, normal weight or overweight.": "Dein Gewicht wird durch deine Körpergröße zum Quadrat geteilt und grob in Kategorien wie Untergewicht, Normalgewicht oder Übergewicht eingeordnet.",
      "IMPORTANT TO KNOW": "WICHTIG ZU WISSEN",
      "BMI does not consider muscle mass, body composition, genetics or athletic performance. A strong athlete can have a higher BMI and still be fit and healthy.": "BMI berücksichtigt weder Muskelmasse noch Körperzusammensetzung, Genetik oder sportliche Leistung. Eine starke athletische Person kann einen höheren BMI haben und trotzdem fit und gesund sein.",
      "USE IT AS A REFERENCE": "NUTZE ES ALS REFERENZ",
      "Numbers can guide you. They do not define you.": "Zahlen können dich orientieren. Sie definieren dich nicht.",
      "BMI REFERENCE RANGES": "BMI-RICHTWERTE",
      "For adults, these ranges are commonly used as a broad orientation. Your training level, muscle mass and overall health context still matter.": "Für Erwachsene werden diese Bereiche häufig als grobe Orientierung genutzt. Trainingslevel, Muskelmasse und dein gesamter Gesundheitskontext bleiben trotzdem wichtig.",
      "LOW": "NIEDRIG",
      "GOOD": "GUT",
      "MEDIUM": "MITTEL",
      "HIGH": "HOCH",
      "Under 18.5": "Unter 18.5",
      "Often classified as underweight.": "Wird oft als Untergewicht eingeordnet.",
      "Usually considered the healthy weight range.": "Gilt meistens als gesunder Gewichtsbereich.",
      "Often classified as overweight, depending on context.": "Wird oft als Übergewicht eingeordnet, abhängig vom Kontext.",
      "30.0 and above": "30.0 und höher",
      "Often classified as obesity and worth discussing in context.": "Wird oft als Adipositas eingeordnet und sollte im Kontext betrachtet werden.",
      "ADVANCED DATA ENCRYPTION PROTOCOL": "ERWEITERTES DATENVERSCHLÜSSELUNGSPROTOKOLL",
      "All biometric data transmitted between your wearables and PROGYM servers is protected by 256-bit military-grade encryption. Your performance is private.": "Alle biometrischen Daten zwischen deinen Wearables und den PROGYM-Servern werden mit militärischer 256-Bit-Verschlüsselung geschützt. Deine Performance bleibt privat.",
      "HIPAA COMPLIANT": "HIPAA-KONFORM",
      "END-TO-END ENCRYPTED": "ENDE-ZU-ENDE VERSCHLÜSSELT",
      "ELEVATE YOUR": "STEIGERE DEINE",
      "PERFORMANCE": "PERFORMANCE",
      "DATA DRIVEN.": "DATENGETRIEBEN.",
      "RESULT FOCUSED.": "ERGEBNISFOKUSSIERT.",
      "SCROLL DOWN": "NACH UNTEN SCROLLEN"
      ,"Barbell": "Hantel",
      "Fire": "Feuer",
      "Activity": "Aktivität",
      "Cycle": "Fahrrad",
      "Yoga": "Yoga",
      "POLICY": "RICHTLINIE",
      "DATA COLLECTION": "DATENERFASSUNG",
      "We capture essential performance metrics: heart rate, HRV, VO2 max, and spatial movement data during sessions.": "Wir erfassen wichtige Performance-Werte wie Herzfrequenz, HRV, VO2max und Bewegungsdaten während deiner Einheiten.",
      "BIOMETRIC INPUT": "BIOMETRISCHE DATEN",
      "MOTION TRACKING": "BEWEGUNGSTRACKING",
      "DATA USAGE": "DATENNUTZUNG",
      "Processed via kinetic algorithms to calculate optimal recovery windows and personalized workload intensity targets.": "Die Daten werden über Bewegungsalgorithmen verarbeitet, um optimale Erholungsfenster und persönliche Belastungsziele zu berechnen.",
      "RECOVERY ANALYTICS": "ERHOLUNGSANALYSEN",
      "LOAD PREDICTION": "BELASTUNGSPROGNOSE",
      "THIRD-PARTY SHARING": "WEITERGABE AN DRITTE",
      "We only sync with ecosystem partners you authorize (Apple Health). Zero data sales to advertisers.": "Wir synchronisieren nur mit Partnern, die du autorisierst (Apple Health). Kein Verkauf von Daten an Werbetreibende.",
      "API INTEGRATIONS": "API-INTEGRATIONEN",
      "SECURE SYNC": "SICHERE SYNCHRONISIERUNG",
      "USER RIGHTS": "NUTZERRECHTE",
      "You own your performance data. Request full exports, data deletion, or portable transfers at any moment.": "Deine Performance-Daten gehören dir. Du kannst jederzeit Exporte, Löschung oder portable Übertragungen anfordern.",
      "DATA PORTABILITY": "DATENPORTABILITÄT",
      "RIGHT TO ERASE": "RECHT AUF LÖSCHUNG",
      "SECURITY PROTOCOLS": "SICHERHEITSPROTOKOLLE",
      "End-to-end encryption for all telemetry data. Multi-factor authentication required for athlete profile access.": "Ende-zu-Ende-Verschlüsselung für alle Telemetriedaten. Für den Profilzugriff ist Mehrfaktor-Authentifizierung erforderlich.",
      "AES-256 ENCRYPTION": "AES-256-VERSCHLÜSSELUNG",
      "2FA PROTECTION": "2FA-SCHUTZ",
      "COOKIES": "COOKIES",
      "Minimalist tracking for session persistence and preference storage. No third-party marketing beacons used.": "Minimales Tracking für Sitzungsfortsetzung und Einstellungen. Keine Marketing-Beacons von Drittanbietern.",
      "SESSION MANAGEMENT": "SITZUNGSVERWALTUNG",
      "USER PREFERENCES": "NUTZEREINSTELLUNGEN",
      "ENTITY": "UNTERNEHMEN",
      "REGISTERED OFFICE": "SITZ",
      "Germany": "Deutschland",
      "REGISTRY COURT": "REGISTERGERICHT",
      "REGISTRY NUMBER": "REGISTERNUMMER",
      "LEGAL REPRESENTATIVES": "GESETZLICHE VERTRETUNG",
      "CEO / MANAGING DIRECTOR": "CEO / GESCHÄFTSFÜHRER",
      "CONTACT DETAILS": "KONTAKTDATEN",
      "EMAIL": "E-MAIL",
      "PHONE": "TELEFON",
      "VAT ID": "UST-ID",
      "ONLINE DISPUTE RESOLUTION": "ONLINE-STREITBEILEGUNG",
      "The European Commission provides a platform for online dispute resolution (ODR), which you can find here: https://ec.europa.eu/consumers/odr. We are neither obliged nor willing to participate in a dispute resolution procedure before a consumer arbitration board.": "Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit: https://ec.europa.eu/consumers/odr. Wir sind weder verpflichtet noch bereit, an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen."
      ,"Start a Workout": "Workout starten",
      "Choose a routine or go freestyle": "Wähle eine Routine oder trainiere frei",
      "Freestyle Workout": "Freies Workout",
      "Log any exercise on the fly.": "Protokolliere jede Übung spontan.",
      "exercises": "Übungen",
      "Session in progress": "Einheit läuft",
      "Finish Routine": "Routine beenden",
      "Set": "Satz",
      "Weight (kg/lb)": "Gewicht (kg/lb)",
      "Weight": "Gewicht",
      "Done": "Erledigt",
      "Add Freestyle Exercise": "Freie Übung hinzufügen",
      "Add Set": "Satz hinzufügen",
      "Session Notes": "Notizen zur Einheit",
      "How did this workout feel?": "Wie hat sich dieses Workout angefühlt?",
      "Progress Tracking": "Fortschritts-Tracking",
      "Visualize your gains over time": "Visualisiere deine Fortschritte über die Zeit",
      "Search exercise (e.g. Squat)": "Übung suchen (z. B. Kniebeuge)",
      "Analyze": "Analysieren",
      "Development over time": "Entwicklung über die Zeit",
      "Loading data...": "Daten werden geladen...",
      "No data found for": "Keine Daten gefunden für",
      "Try logging some workouts first!": "Protokolliere zuerst ein paar Workouts!",
      "Max Weight": "Max. Gewicht",
      "Max Reps": "Max. Wiederholungen",
      "Workout Plans": "Workout-Pläne",
      "Manage your routines": "Verwalte deine Routinen",
      "New Plan": "Neuer Plan",
      "Create New Plan": "Neuen Plan erstellen",
      "Plan Name": "Planname",
      "e.g. Push Day": "z. B. Push Day",
      "Description": "Beschreibung",
      "Optional description": "Optionale Beschreibung",
      "Exercises": "Übungen",
      "sets x": "Sätze x",
      "reps": "Wdh.",
      "Add": "Hinzufügen",
      "Cancel": "Abbrechen",
      "Save Plan": "Plan speichern",
      "Reps (e.g. 8-12)": "Wdh. (z. B. 8-12)"
      ,"Sets": "Sätze",
      "Reps": "Wdh."
      ,"ABOUT US": "ÜBER UNS",
      "FOUNDERS": "GRÜNDER",
      "THE DEVELOPER": "DIE ENTWICKLERIN",
      "THE DESIGNER": "DER DESIGNER",
      "Technical Lead - Focused on software architecture and data logic. She builds the robust engine behind PROGYM, ensuring every rep and set is recorded with precision and backed by reliable engineering.": "Technical Lead - Fokussiert auf Softwarearchitektur und Datenlogik. Sie baut den robusten Motor hinter PROGYM und sorgt dafür, dass jede Wiederholung und jeder Satz präzise erfasst und technisch zuverlässig verarbeitet wird.",
      "Creative Lead - Specializing in UI/UX and visual strategy. He transforms complex workout data into a clean, intuitive experience, ensuring that tracking your progress is as seamless as the workout itself.": "Creative Lead - Spezialisiert auf UI/UX und visuelle Strategie. Er verwandelt komplexe Workout-Daten in eine klare, intuitive Erfahrung, damit dein Fortschritt so nahtlos getrackt wird wie das Workout selbst.",
      "THE TEAM BEHIND": "DAS TEAM HINTER",
      "started with a simple vision: we were tired of tattered notebooks and losing track of our progress between sets. We built this digital home to replace pens and paper with a seamless, intelligent platform for your hard work. From tracking every rep to visualizing long-term growth, we created the tool we always wanted for our own journey. No more guessing, just pure progress.": "entstand aus einer einfachen Vision: Wir hatten genug von zerfledderten Notizbüchern und davon, zwischen den Sätzen den Fortschritt aus den Augen zu verlieren. Wir haben dieses digitale Zuhause gebaut, um Stift und Papier durch eine nahtlose, intelligente Plattform für harte Arbeit zu ersetzen. Vom Tracken jeder Wiederholung bis zur Visualisierung langfristigen Wachstums haben wir das Tool geschaffen, das wir uns selbst immer gewünscht haben. Kein Rätselraten mehr, nur echter Fortschritt.",
      "ACTIVE ATHLETES": "AKTIVE ATHLETEN",
      "USERS": "NUTZER",
      "OUR": "UNSERE",
      "PHILOSOPHY": "PHILOSOPHIE",
      "PRECISION": "PRÄZISION",
      "Every rep is a data point. We don't guess - we calculate. Minimal effort for maximum metabolic disruption.": "Jede Wiederholung ist ein Datenpunkt. Wir raten nicht - wir berechnen. Minimaler Aufwand für maximale metabolische Wirkung.",
      "INTENSITY": "INTENSITÄT",
      "Comfort is the enemy of progress. We design for the threshold where physical limits are redefined.": "Komfort ist der Feind des Fortschritts. Wir gestalten für die Schwelle, an der körperliche Grenzen neu definiert werden.",
      "EVOLUTION": "EVOLUTION",
      "The body is a machine that must be upgraded constantly. Stagnation is not an option in the PROGYM ecosystem.": "Der Körper ist eine Maschine, die ständig verbessert werden muss. Stillstand ist im PROGYM-Ökosystem keine Option."
    }
  };

  const t = (key, params = {}) => {
    const translation = dictionary[lang][key] || key;
    return Object.entries(params).reduce(
      (text, [paramKey, value]) => text.replaceAll(`{${paramKey}}`, value),
      translation
    );
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
